services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LOG4J_LOGGERS: "state.change.logger=WARN,kafka=WARN"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  order:
    build: ./order
    container_name: order
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  user:
    build: ./user
    container_name: user
    ports:
      - "8081:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  payment:
    build: ./payment
    container_name: payment
    ports:
      - "8082:8080"

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8083:8080"
    environment:
      SERVER_PORT: 8080
      KAFKA_HOST: kafka:29092
      PAYMENT_HOST: payment:8080
    depends_on:
      - kafka
      - payment