CREATE TABLE ONLINE_ORDERS (
    ID VARCHAR(255) PRIMARY KEY,
    PAYMENT_STATUS VARCHAR(255) NOT NULL,
    USER_STATUS VARCHAR(255) NOT NULL,
    ORDER_STATUS VARCHAR(255) NOT NULL,
    IS_COMPENSATED VARCHAR(1) NOT NULL
);